[package]
name = "derive_display"
authors = ["orgrinrt", "Hiisi Digital"]
version = "0.0.5"
edition = "2021"
rust-version = "1.70"
description = """
An attribute to derive a `Display` implementation from another trait implementation, currently `ToTokens`.
"""
license = "MPL-2.0"
readme = "README.md"
keywords = ["derive", "trait", "impl", "display", "helper"]
categories = ["rust-patterns", "value-formatting", "development-tools", "development-tools::procedural-macro-helpers"]
documentation = "https://docs.rs/derive_display"
homepage = "https://github.com/orgrinrt/derive_display"
repository = "https://github.com/orgrinrt/derive_display"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0"

[dependencies]
include_proc_macro = "2.0"
syn = { version = "2.0.68", default-features = false, features = ["full", "parsing", "proc-macro", "printing"] }
quote = "1.0.36"
proc-macro2 = { version = "1.0.86", features = [] }
